### ISSUE TITLE
Multiple roles when adding a staff member

### ISSUE THREAD

**Issue by Briesmas** [cory2067/gtsosu#48]
I think the title is pretty clear. Currently each role has to be added separately when adding a staff member. I tagged as good for first issue but I'm not exactly sure how complicated this is? I believe it shouldn't be too hard.

**Comment by cory2067** [comment]
First, you'll need to make the role select a multi select field 
Docs: https://ant.design/components/select/

And then for the rest,
Legit way:
This will require modifying the api route for `/api/staff` to accept an array of `roles` instead of a single string `role`. Then modifying that mongo query to insert multiple roles at once
These docs may help: https://docs.mongodb.com/manual/reference/operator/update/each/

Easy way:
Send out multiple requests to `/api/staff`, once per each role
